(function(){
const STORAGE_KEY='laya_pet_puppet_mode_v1';
const defaultState={coin:120,score:78,hunger:78,energy:64,happy:86,clean:71,bond:82,mood:'idle',lastSavedAt:null,lastPlayedAt:Date.now()};
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?{...defaultState,...JSON.parse(raw)}:{...defaultState}}catch(e){return {...defaultState}}}
const state=loadState();
const petImg=document.getElementById('petImg');
const petStage=document.getElementById('petStage');
let microTimer=null,blinkTimer=null;
const moodDescriptions={idle:'ดุ๊กดิ๊กเบาๆ แบบมีชีวิต',happy:'เด้งถี่ขึ้นเพราะมีความสุข',love:'อบอุ่นและมีหัวใจลอยรอบตัว',sad:'เคลื่อนไหวช้าลงเหมือนงอแง',sleep:'พักผ่อน ลอยช้า และหลับตา',hurt:'สะดุ้งเล็กน้อยเมื่อเสียใจ',attack:'พลังงานสูงและกระฉับกระเฉง',dash:'พลังงานสูงมากและขยับไว'};
const speechs={idle:'ตอนนี้น้องจะดุ๊กดิ๊กแบบมีชีวิตมากขึ้นแล้ว 💖',happy:'ดีใจที่สุดเลย! ✨',love:'ความผูกพันของเราอบอุ่นมาก 💗',sad:'วันนี้ขออยู่ใกล้ๆได้ไหม',sleep:'ขอพักสักหน่อยนะ… Zz',hurt:'โอ๊ย… แต่ฉันยังไหว',attack:'ฉันพร้อมอยู่ตรงนี้นะ',dash:'วันนี้พลังล้นเลย!'};
const clamp=v=>Math.max(0,Math.min(100,v));
function inferMood(){if(state.energy<=20)return'sleep'; if(state.hunger<=20||state.clean<=20)return'sad'; if(state.happy<=18)return'hurt'; if(state.bond>=88&&state.happy>=75)return'love'; if(state.happy>=80)return'happy'; return'idle';}
function saveState(showLog=false){state.lastSavedAt=Date.now(); localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); updateSaveLabels(); if(showLog)pushLog('💾','Save','บันทึกสถานะปัจจุบันแล้ว');}
function updateSaveLabels(){const text=state.lastSavedAt?`💾 Saved ${new Date(state.lastSavedAt).toLocaleTimeString()}`:'💾 ยังไม่เคยบันทึก'; ['saveStateLabel','saveStateLabelDesktop'].forEach(id=>{const el=document.getElementById(id); if(el)el.textContent=text;});}
function renderBars(prefix=''){[['Hunger',state.hunger],['Energy',state.energy],['Happy',state.happy],['Clean',state.clean],['Bond',state.bond]].forEach(([k,v])=>{const bar=document.getElementById('bar'+k+prefix),txt=document.getElementById('txt'+k+prefix); if(bar)bar.style.width=v+'%'; if(txt)txt.textContent=v+'%';});}
function renderAll(){['','D'].forEach(renderBars); document.getElementById('coinDisplay').textContent=`🪙 ${state.coin}`; document.getElementById('scoreDisplay').textContent=`📈 Score ${state.score}`; document.getElementById('speechBubble').textContent=speechs[state.mood]; document.getElementById('petSub').textContent=moodDescriptions[state.mood]; petStage.className=`pet-stage ${state.mood}`; updateSaveLabels();}
function pushLog(icon,title,text){const html=`<div class="log-item"><div class="log-icon">${icon}</div><div class="log-text"><strong>${title}</strong><span>${text}</span></div></div>`; ['logArea','logAreaDesktop'].forEach(id=>{const el=document.getElementById(id); if(!el)return; el.insertAdjacentHTML('afterbegin',html); while(el.children.length>5)el.removeChild(el.lastElementChild);});}
function resetMicro(){petImg.classList.remove('micro-pop','micro-squish','micro-tilt-left','micro-tilt-right','micro-hop');}
function triggerMicro(type){resetMicro(); void petImg.offsetWidth; petImg.classList.add(type); setTimeout(()=>petImg.classList.remove(type),260);}
function triggerBlink(){if(state.mood==='sleep')return; petStage.classList.remove('blink'); void petStage.offsetWidth; petStage.classList.add('blink'); setTimeout(()=>petStage.classList.remove('blink'),220);}
function scheduleBlink(){clearTimeout(blinkTimer); blinkTimer=setTimeout(()=>{triggerBlink(); scheduleBlink();},2200+Math.random()*3200);}
function scheduleMicro(){clearTimeout(microTimer); microTimer=setTimeout(()=>{const c=state.mood; const pool=c==='sleep'?['micro-squish']:c==='sad'?['micro-tilt-left','micro-tilt-right','micro-squish']:c==='happy'||c==='love'?['micro-pop','micro-hop','micro-tilt-left','micro-tilt-right']:['micro-pop','micro-squish','micro-tilt-left','micro-tilt-right','micro-hop']; triggerMicro(pool[Math.floor(Math.random()*pool.length)]); scheduleMicro();},1700+Math.random()*2400);}
function handleAction(action){if(action==='feed'){state.hunger=clamp(state.hunger+16); state.happy=clamp(state.happy+4); state.coin+=2; pushLog('🍓','Feed','Nova อิ่มขึ้นและอารมณ์ดีขึ้น'); triggerMicro('micro-pop');} if(action==='play'){state.happy=clamp(state.happy+14); state.energy=clamp(state.energy-8); state.bond=clamp(state.bond+3); pushLog('🎮','Play','Nova ดุ๊กดิ๊กแรงขึ้นและ bond เพิ่ม'); triggerMicro('micro-hop');} if(action==='clean'){state.clean=clamp(state.clean+18); state.happy=clamp(state.happy+3); pushLog('🛁','Clean','ตัวน้องสดชื่นและดูสบายใจขึ้น'); triggerMicro('micro-tilt-right');} if(action==='sleep'){state.energy=clamp(state.energy+20); state.hunger=clamp(state.hunger-4); pushLog('😴','Sleep','Nova พักผ่อนและฟื้นพลัง'); triggerMicro('micro-squish');} state.lastPlayedAt=Date.now(); state.mood=inferMood(); saveState(); renderAll();}
function resetState(){localStorage.removeItem(STORAGE_KEY); Object.assign(state,{...defaultState,lastPlayedAt:Date.now()}); pushLog('🗑️','Reset Save','ล้างข้อมูลและเริ่มใหม่เรียบร้อย'); saveState(); renderAll();}
document.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>handleAction(btn.dataset.action))); ['saveNowBtn','saveNowBtnDesktop'].forEach(id=>{const el=document.getElementById(id); if(el)el.addEventListener('click',()=>saveState(true));}); ['resetSaveBtn','resetSaveBtnDesktop'].forEach(id=>{const el=document.getElementById(id); if(el)el.addEventListener('click',resetState);}); const elapsed=Math.floor((Date.now()-(state.lastPlayedAt||Date.now()))/12000); if(elapsed>0){state.hunger=clamp(state.hunger-elapsed); state.energy=clamp(state.energy-elapsed); state.clean=clamp(state.clean-elapsed); state.lastPlayedAt=Date.now();} state.mood=inferMood(); pushLog('🫧','Pet Puppet Mode','รอบนี้รื้อเฉพาะเวที pet ให้ดูมีชีวิตขึ้น'); renderAll(); scheduleBlink(); scheduleMicro();
})();
